[project]
name = "scripts"
version = "0.1.0"
description = "scripts for preprocessing fortune cookies"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "loguru>=0.7.2",
    "requests>=2.32.3",
]
